language: node_js
node_js:
- '0.12'
sudo: false
cache:
  directories:
  - node_modules
before_install:
- export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
- npm config set spin false
- npm install -g npm@^2
install:
- npm install -g bower
- npm install
- bower install
script:
- npm test
deploy:
  provider: s3
  local_dir: dist
  access_key_id: AKIAJGVITZIKV3S4AO7A
  secret_access_key:
    secure: s+8Q0z9fmuwCDZrnz7rwlN/VZiNZrgsEvOERvH9lgtDh5LarLu1eWWJU62RMik+bUfZRFN0d5u3wo0FBLmiB5tHyPTNSkeFv8rMoT30z5uyHAHe7Vov6iKl8xykNK7Fl95Clg/K+OdtpsIWDezPrQqOifDeRfAxIF8j2wtgcaWoFwLiQ4yxK+fr8J9seubq22uip/o476HsKpA9Wm1XYOyrsolaoL1EoIlNrw5/kBEHpXN5kQfL4MdJhbBP7o4ZcBjAjqmjqKxJHmCmt8G/r2NwRMoJ9Nl0J8WcZhjoktWq/u87cnClOC1X4DDxyYV4SDy9KIdDEFhe6AW0TGiAF1ccvdkIy8br26aH1ItPM4qtTXtdMnU4LFikzle/fUAI9zSWKYQTR7qZHQ9KYR7qQd7a2gmVNzOa8bUNvRny6B8B1or2jkeLKqZ9z0bk0J3dDIRbFFN0kfaQdaw92m73wbCcDcPiwlW5mNgnDItBkj6DMTzuJK1hGzntJg+3G/29orvH39SvcZztnHusjR5ANEZqX1v9JKPEdVhRKRRL2GuCKDSElyJYIAOterfHlITfqJ2J4Fh1f98zczqBCxq+IHsnJSD8/VGgpuheM9aXXoFB1TpZiynPB2iAzgWh4eH8f5IJQ2bQf/oNFPXow29bKUOCcYAbVcFyLALBQHL+ZIFE=
  bucket: www.kennethbuck.ca
  acl: public_read
  on:
    repo: kennethdavidbuck/benson
    branch: develop
